$(document).ready(function () {
	$("#virool").attr("src", "http://api.virool.com/widgets/06a00dbd598e13de0dc5f25f56499892?width=640&height=400")
});
setTimeout(function () {
	$("#virool").attr("src", "http://api.virool.com/widgets/06a00dbd598e13de0dc5f25f56499892?width=640&height=400")
}, 30 * 60 * 1000);
setTimeout(function () {
	$("#wepay_button").append('<a class="wepay-widget-button wepay-green" id="wepay_widget_anchor_5253c939903fb" href="https://www.wepay.com/donations/688372794">Support Ongoing Development!</a><script type="text/javascript">var WePay = WePay || {};WePay.load_widgets = WePay.load_widgets || function() { };WePay.widgets = WePay.widgets || [];WePay.widgets.push( {object_id: 688372794,widget_type: "donation_campaign",anchor_id: "wepay_widget_anchor_5253c939903fb",widget_options: {list_suggested_donations: true,allow_cover_fee: true,enable_recurring: true,allow_anonymous: true,reference_id: ""}});if (!WePay.script) {WePay.script = document.createElement(\'script\');WePay.script.type = \'text/javascript\';WePay.script.async = true;WePay.script.src = \'https://static.wepay.com/min/js/widgets.v2.js\';var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(WePay.script, s);} else if (WePay.load_widgets) {WePay.load_widgets();}<\/script>');
	$("#wepay_progress").append('<a class="wepay-widget-button wepay-green" id="wepay_widget_anchor_5253cd9bc8473" href="https://www.wepay.com/donations/688372794">View Progress</a><script type="text/javascript">var WePay = WePay || {};WePay.load_widgets = WePay.load_widgets || function() { };WePay.widgets = WePay.widgets || [];WePay.widgets.push( {object_id: 688372794,widget_type: "donation_campaign_progress",anchor_id: "wepay_widget_anchor_5253cd9bc8473",widget_options: {no_dialog: "true",total_collected: "true"}});if (!WePay.script) {WePay.script = document.createElement(\'script\');WePay.script.type = \'text/javascript\';WePay.script.async = true;WePay.script.src = \'https://static.wepay.com/min/js/widgets.v2.js\';var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(WePay.script, s);} else if (WePay.load_widgets) {WePay.load_widgets();}<\/script>')
}, 1000);